name: ColorText
version: 0.1 Alpha
api: [1.2.0]
author: Heromine
description: will be add soon...
main: ColorText\ColorText

commands:
  color:
    permission: true
    description: Change text color
