name: ColorText
version: 1.1.0
api: [1.4.0]
author: Heromine
main: ColorText\ColorText
description: Chat in color
commands:
    color:
        permission: Color.color
        description: Change messages color(First do /discolor)
    discolor:
        permission: Color.discolor
        description: Disable color plugin if you are in MCPE
permissions:
    color:
        default: true
        description: Color command
        children:
            color.color:
                default: true
                description: "Color: enable colors for BlockLauncher users"
            color.discolor:
                default: true
                description: "Discolor: disable colors for MCPE users"
