name: ColorText
version: 1.4.0
api: [1.4.0]
author: Heromine
main: ColorText\ColorText
description: Chat in color
commands:
    color:
        permission: Color.color
        description: Change messages color
        usage: "/color"
permissions:
    color:
        default: true
        description: Color command
        children:
            color.color:
                default: true
                description: "Color: enable colors for BlockLauncher users"
