name: ColorText
version: 1.0.0
api: [1.0.0]
author: Heromine
main: ColorText\ColorText
description: Chat in color
commands:
    color:
        permission: Color.color
        description: Change text color
permission:
    color:
        default: op
        description: Color command
        children:
            Color.color:
                default: op
                description: "Color"
